### ISSUE TITLE
I have some problem to run example

### ISSUE THREAD

**Issue by leeseulbiit** [peduajo/geetest-slice-captcha-solver#2]
`Traceback (most recent call last):  File ".\test.py", line 3, in <module>    solution = solver.get_position()
  File "C:\Users\Admin\Desktop\geetest-slice-captcha-solver-master\geetest-slice-captcha-solver-master\solver.py", line 16, in get_position
    res = cv2.matchTemplate(background, template, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:589: error: (-215:Assertion failed) corrsize.height <= img.rows +
templ.rows - 1 && corrsize.width <= img.cols + templ.cols - 1 in function 'cv::crossCorr'`

**Comment by spdragon** [comment]
i think the problem is on the size of the image

**Comment by spdragon** [comment]
> `Traceback (most recent call last): File ".\test.py", line 3, in <module> solution = solver.get_position() File "C:\Users\Admin\Desktop\geetest-slice-captcha-solver-master\geetest-slice-captcha-solver-master\solver.py", line 16, in get_position res = cv2.matchTemplate(background, template, cv2.TM_CCOEFF_NORMED) cv2.error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:589: error: (-215:Assertion failed) corrsize.height <= img.rows + templ.rows - 1 && corrsize.width <= img.cols + templ.cols - 1 in function 'cv::crossCorr'`

hey somehow i fixed it, in the __img_to_grayscale function, change the temp path to a full path, for example "C:/Users/User-PC/Download/geetest-slice-captcha-solver-master/example/sobel.png". It worked after the changed.

**Comment by leeseulbiit** [comment]
> > `Traceback (most recent call last): File ".\test.py", line 3, in <module> solution = solver.get_position() File "C:\Users\Admin\Desktop\geetest-slice-captcha-solver-master\geetest-slice-captcha-solver-master\solver.py", line 16, in get_position res = cv2.matchTemplate(background, template, cv2.TM_CCOEFF_NORMED) cv2.error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:589: error: (-215:Assertion failed) corrsize.height <= img.rows + templ.rows - 1 && corrsize.width <= img.cols + templ.cols - 1 in function 'cv::crossCorr'`
> 
> hey somehow i fixed it, in the __img_to_grayscale function, change the temp path to a full path, for example "C:/Users/User-PC/Download/geetest-slice-captcha-solver-master/example/sobel.png". It worked after the changed.

ok i will try now. thank you

**Comment by leeseulbiit** [comment]
it's work. thank you so much

**Comment by leeseulbiit** [comment]
do you have code to Examples to work in browser like selenium?

**Comment by anh-collab** [comment]
I keep getting the same error even after putting in the full path as @spdragon suggested. Any idea? :(

`File "test.py", line 4, in <module>
    solution = solver.get_position()
  File "D:\Sil\Collab\China\bilibili-scraper-windows\scraper\external\solver.py", line 16, in get_position
    res = cv2.matchTemplate(background, template, method=cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:589: error: (-215:Assertion failed) corrsize.height <= img.rows + templ.rows - 1 && corrsize.width <= img.cols + templ.cols - 1 in function 'cv::crossCorr'`

**Comment by mrluaf** [comment]
I can't find sobel.png in example folder.

**Comment by GodStar88** [comment]
def __piece_preprocessing(self):
        img = self.__sobel_operator(self.piece_path)
        x, w, y, h = self.__crop_piece(img)
        template = img[y:h, x:w]
        template = self.__extend_template_boundary(template)
        template = self.__img_to_grayscale(template)
        print(template)
        print(x)
        print(y)
        print(h)
        return template, x, y, h
